### ISSUE TITLE
Support for SASL-SCRAM-256

### ISSUE THREAD

**Issue by adfoster-r7** [jeremyevans/sequel-postgres-pr#2]
Hi there,

I only came across this fork today, we don't curently use sequel-postgres-pr right now - but I thought it might be worth calling out that our vendored dependency of the upstream `postgres-pr` repo has been recently updated to support SASL-SCRAM-256 Auth. So if any of your Sequel gem users need that support, the original issue might be worth cross-referencing :+1:

**Comment by jeremyevans** [comment]
Thanks for pointing that out.  Do you have a direct link for the commit(s) adding SASL-SCRAM-256 support?

I'm going to close this now as it isn't a bug in the library, but we can continue discussion of this possible new feature.

**Comment by adfoster-r7** [comment]
Sorry - I meant to cross-reference the original issue - https://github.com/mneumann/postgres-pr/issues/10

The issue above has the link to the code changes made, as well as the offer to contribute the work to the original library implementation - but I didn't realize the original project was unmaintained when I posted it

I don't think there's anything actionable right now, I just wanted to post here as well for visibility incase you get feature requests for it - and wanted to help save any potential duplication of effort there; thanks! :+1:

**Comment by jeremyevans** [comment]
I think that's something I would be willing to accept, as long as it didn't include the unnecessary whitespace changes.  Coverage testing such code would be challenging, but let me know if you have ideas on that (this library maintains 100% line/branch coverage).
