### ISSUE TITLE
Cannot connect to PostgreSQL server 16.1

### ISSUE THREAD

**Issue by postmodern** [jeremyevans/sequel-postgres-pr#3]
Getting an error when attempting to connect to a PostgreSQL 16.1 server.

## Steps To Reproduce

```ruby
require 'postgres-pr/connection'

PostgresPR::Connection.new('localhost', 5432, nil, nil, 'db', 'admin', 'password1234')
```

### Expected Result

Connects.

### Actual Result

```
/data/home/postmodern/code/ronin-rb/vendor/bundle/ruby/3.1.0/gems/sequel-postgres-pr-0.9.0/lib/postgres-pr/message.rb:67:in `parse': #<PostgresPR::Buffer:0x00007fdea53c01f0 @size=24, @content="R\u0000\u0000\u0000\u0017\u0000\u0000\u0000\nSCRAM-SHA-256\u0000\u0000", @position=9> (PostgresPR::ParseError)
	from /data/home/postmodern/code/ronin-rb/vendor/bundle/ruby/3.1.0/gems/sequel-postgres-pr-0.9.0/lib/postgres-pr/message.rb:97:in `parse'
	from /data/home/postmodern/code/ronin-rb/vendor/bundle/ruby/3.1.0/gems/sequel-postgres-pr-0.9.0/lib/postgres-pr/message.rb:88:in `create'
	from /data/home/postmodern/code/ronin-rb/vendor/bundle/ruby/3.1.0/gems/sequel-postgres-pr-0.9.0/lib/postgres-pr/message.rb:35:in `read'
	from /data/home/postmodern/code/ronin-rb/vendor/bundle/ruby/3.1.0/gems/sequel-postgres-pr-0.9.0/lib/postgres-pr/connection.rb:49:in `initialize'
```

## Version Information

* sequel-postgres-pr 0.9.0

**Comment by jeremyevans** [comment]
I doubt this is a bug.  sequel-postgres-pr doesn't currently support
SCRAM-SHA-256 authentication.  You'll need to pick a different
authentication method on the server currently if you want to use
sequel-postgres-pr on the client.

See #2.

**Comment by postmodern** [comment]
@jeremyevans seems like a bug since it's failing to parse a default configured postgresql server. I think it would be more helpful if you detected SCRAM-SHA-256 and raised a `NotImplementedError` exception explaining that it's not supported.

**Comment by jeremyevans** [comment]
I'm not sure what the mean by `default configured postgresql server`.  SCRAM-SHA-256 is not turned on by default by PostgreSQL `initdb`.  You have to use the `-A`/`--auth` option to `initdb` to turn on authentication, and then it uses what you select.   Maybe you are using some packaging system that is setting SCRAM-SHA-256 by default, but that is not the PostgreSQL default.  Currently, you shouldn't force SCRAM-SHA-256 if you want to use sequel-postgres-pr.

In terms of a nicer error message, how about this?:

```diff
diff --git a/lib/postgres-pr/message.rb b/lib/postgres-pr/message.rb
index fe1f352..db11e50 100644
--- a/lib/postgres-pr/message.rb
+++ b/lib/postgres-pr/message.rb
@@ -98,6 +98,8 @@ module PostgresPR
         @auth_type = buffer.read_int32
         yield if block_given?
       end
+    rescue ParseError => e
+      raise PGError, "unsupported authentication type: #{@auth_type} buffer: #{buffer.content[buffer.position..-1].inspect}", e.backtrace
     end
   end

```

As I mentioned in #2, I'm open to supporting SCRAM-SHA-256 if someone can submit a working patch for it.

**Comment by postmodern** [comment]
@jeremyevans the version of postgres in the [postgres:latest](https://hub.docker.com/_/postgres) docker image does have SCRAM-SHA-256 enabled by default.

```dockerfile
FROM postgres:latest

ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD password1234
ENV POSTGRES_DB db
```

**Comment by adfoster-r7** [comment]
I think I posted this context on one of the other issues, but since this one has been recently referenced I'll mentioned it here too. I've made similar changes to support postgres's newer SASL/SCRAM auth over in Metasploit-framework: https://github.com/rapid7/metasploit-framework/pull/18276

If I understand the history correctly - Metasploit framework uses an old vendored version of the code that this repository was also forked from. I still haven't had any cycles to contribute this upstream to either this repo or the original repo - but I'm happy for anyone to take the code or inspiration from the framework changes to make that happen :+1:
